{% set name = "PyTrie" %}
{% set version = "0.4.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8f4488f402d3465993fb6b6efa09866849ed8cda7903b50647b7d0342b805379" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - sortedcontainers

test:
  imports:
    - pytrie
  commands:
    - pip check
  requires: 
    - pip
  
about:
  home: https://github.com/gsakkis/pytrie
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A pure Python implementation of the trie data structure.'
  dev_url: https://github.com/gsakkis/pytrie
  doc_url: https://pytrie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
