travis:
  secure:
    BINSTAR_TOKEN: DNEUsUueatG/tMSEj5aaHEPMon+jA8/C+rmrZ+TY/ac10MKuZn8eulVCCU1VDZ2mdV9lIOa9Iu7uP6qlSEf9p23uqCj+kQTDwjxq0LB0j+QRZfLgvo4FLDdMO4ttgztH+ZHP+UcTyjO+2LU8Tu7pbPac+7agIyqYcZCrgZa3qKj7FG3NH2BeU3BJuNWS5737S3RjnUvqbJewzmRvjoPIEG/OrnR2icILCQXWQMtIasxIr3t1kaf08oVJR9oKCcZcrsgjuMKW+o/87ZWmGf22c+FF61X4DYsVrRRIf/bYeDLDsUMnf06fW6+Bs/KucPEeVd/0zgqtgvCHeTR8QYBOJs8LK+EELqIfsX2Gkk74Dw+zDhTvbmx/WGtgEQ927NAWlGQA+SxpfXErB7enp7gOtTzfsxZKNEqCCs8uqDY7+GONsfQ5GstyXf1OwY8iTvVnoXjR9HqmtJrwI5k7qYDhyNgyfd9mFFkTpdoQq4ApcSfe+ldIou5tiNh2iMIIHBbuqsO5+jUua1UAjNa51kCUq91DQIADNURMGvUQEWN/ZN2mhFkMOjG3CTYeSx5rF+KSqO574OKoH1+ZM2SRoeVU9ZcpWjnBS9HwM9YnepruXNooNxpctf6LbfDbF1jWaxUApCAGe/UFKdz+G3A0AH5+hNm/T1eA3jhOOja38CIeALw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
