travis:
  secure:
    BINSTAR_TOKEN: e8wOBPb7HirhkYmnKlSPb4xbeTqZGp8J72Kj1OobyhSkCwCLNZjM+n+XJAKwuZrQmh4qRoCDrUuqr5SNccPd249IERO1Dmx7qv5H9tp15JdJVsEEWpPvDMU9aHTFt9bn9Ln+jpv5wKwhUOLqkBwbD7b4N3MR7bRgaL2th8pUwWKU0jyV3bkuwfbNkpMQkMvvMcTLfYeEA9bK/G8y4pOPNxcndb2RmciXdifeen+n79IaiiTzFeWrRlsirdbekobTHgj58x25KoIcZnv8wa85lpoWbumG+/lBwR/UMshlgTW4aTlraSA8GOfhkzXZd5z8MXdXkWYWkZ0++BH6DGbAvACEC8vEl4EWqKfYgHrymwnojL6Fx99QomqyIKRv24vpV94ulqbb/5kOzl2CXddmCnMfaT5Yv6yrYbsh7JgpQsLD2gv29xCx2vdoMWewrcOBmzAehsUHIweWp/YVCPzyoDl9EBUrEUrI5EgU8hMbeRaJ6SpD+yY8XfI23rU2lkUuotK6uawEn0f/RWDtq5egY31Mz9qEwSUaRraC0svelbEZzPSPjQFyun0AYFXZ6EBHm2ZJ2M/FXJhFk0kik/AOBIYroLm2lJtahQnKYT1OYfF+05tOSlDhP0VQT50sHetnQqlhNGGVxBBZKiFqii5sKOKVzneEFGyDGrwJWI17/YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
